name: Deploy API Docs

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build project
        run: mvn clean package -DskipTests

      - name: Start Spring Boot app
        run: |
          java -jar target/*.jar &
          sleep 20

      - name: Download OpenAPI spec
        run: |
          mkdir -p target/generated-docs
          curl http://localhost:8080/v3/api-docs -o target/generated-docs/openapi.json

      - name: Generate HTML docs
        run: |
          npm install -g @openapitools/openapi-generator-cli
          openapi-generator-cli generate \
          -i target/openapi.json \
          -g html2 \
          -o docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs